//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arhiv.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class zayavka
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual users users { get; set; }
    }
}
